# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: rico.njoroge@njuguna.com
author_name: Ricodonto
contract_name: counter
deployment_language: python
preset_name: starter
project_name: Algorand

